version: "3.5"

services: 
  boilerplate-nextjs:
   container_name: boilerplate-nextjs
   build: 
    context: .
    dockerfile: Dockerfile.dev
   restart: always
   ports:
    - 3000:3000
   volumes:
    - .:/app/boilerplate-nextjs
    - /app/boilerplate-nextjs/node_modules
    - /app/boilerplate-nextjs/.next
 
