import React from 'react'
import { LayoutProvider } from '@/providers'
import 'react-toastify/dist/ReactToastify.css'
import './globals.css'

export const metadata = {
  title: 'Boilerplate nextjs',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body>
        <LayoutProvider>{children}</LayoutProvider>
      </body>
    </html>
  )
}
