name: CI
on:
  pull_request:
    branches:
      - production
      - development
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout do repositorio
         uses: actions/checkout@v1
       - name: Criando env
         run: |
          touch .env
          cat .env.example >> .env
       - name: Setup Node
         uses: actions/setup-node@v1
         with:
           node-version: "16.x" 
       - name: Install dependencies
         run: npm ci 
       - name: Checking types
         run: npx tsc
       - name: Running tests
         run: npm run test:silent 
      
